# Generated by Django 4.0.5 on 2022-06-18 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entrada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('md', models.CharField(max_length=1000)),
                ('pares', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Saida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=400)),
                ('paReq', models.CharField(max_length=1000)),
                ('termUrl', models.CharField(max_length=1000)),
                ('md', models.CharField(max_length=1000)),
            ],
        ),
    ]
